# Gitorious database configuration

# The following configuration uses the embedded MySQL instance. Feel free to
# change it to your own MySQL instance address.

# NOTE: "localhost" refers to the container. If you want to use container's host
# machine as db host then use IP address or FQDN instead.

production:
  adapter: mysql2
  database: gitorious
  username: gitorious
  password: yourpassword
  host: localhost
  encoding: utf8
