git clone git@gitorious.org:gitorious/ce-installer.git
git clone git@gitorious.org:gitorious/ci-puppet.git
git clone git@gitorious.org:gitorious/dmca.git
git clone git@gitorious.org:gitorious/docker-memcached.git
git clone git@gitorious.org:gitorious/docker-mysql.git
git clone git@gitorious.org:gitorious/docker-postfix.git
git clone git@gitorious.org:gitorious/docker-redis.git
git clone git@gitorious.org:gitorious/dolt.git
git clone git@gitorious.org:gitorious/force_utf8.git
git clone git@gitorious.org:gitorious/git-archive-daemon.git
git clone git@gitorious.org:gitorious/git-http-multi-backend.git
git clone git@gitorious.org:gitorious/gitorious-book.git
git clone git@gitorious.org:gitorious/gitorious-build.git
git clone git@gitorious.org:gitorious/gitorious-daemons.git
git clone git@gitorious.org:gitorious/gitorious-docker.git
git clone git@gitorious.org:gitorious/gitorious-issues.git
git clone git@gitorious.org:gitorious/gitorious-mirrors.git
git clone git@gitorious.org:gitorious/gitorious-munin-plugins.git
git clone git@gitorious.org:gitorious/gitorious-proto.git
git clone git@gitorious.org:gitorious/gitorious-search.git
git clone git@gitorious.org:gitorious/gitorious-smoke-tests.git
git clone git@gitorious.org:gitorious/issues.git
git clone git@gitorious.org:gitorious/jgit-http-server.git
git clone git@gitorious.org:gitorious/just_paginate.git
git clone git@gitorious.org:gitorious/libdolt.git
git clone git@gitorious.org:gitorious/mainline.git
git clone git@gitorious.org:gitorious/makeup.git
git clone git@gitorious.org:gitorious/merge-request-cli.git
git clone git@gitorious.org:gitorious/mutt.git
git clone git@gitorious.org:gitorious/openid_auth.git
git clone git@gitorious.org:gitorious/packer-templates.git
git clone git@gitorious.org:gitorious/reflog-fun.git
git clone git@gitorious.org:gitorious/status-site.git
git clone git@gitorious.org:gitorious/tiltout.git
git clone git@gitorious.org:gitorious/ui3.git
git clone git@gitorious.org:gitorious/uinit.git
git clone git@gitorious.org:gitorious/use_case.git
git clone git@gitorious.org:gitorious/when-rb.git
git clone git@gitorious.org:gitorious/zuul.git
