#!/bin/bash

set -e

HOST_DATA_DIR="/var/lib/gitorious"
CIDFILE="$HOST_DATA_DIR/gitorious.cid"
HTTP_PORT=7080
SSH_PORT=7022
GIT_PORT=9418

case "$1" in
  start)
    echo "Starting Gitorious container..."
    VOLUME_OPTIONS="-v $HOST_DATA_DIR:/var/lib/gitorious"
    PORT_OPTIONS="-p $HTTP_PORT:80 -p $SSH_PORT:22 -p $GIT_PORT:9418"
    OTHER_OPTIONS="-d -cidfile $CIDFILE"
    IMAGE="gitorious/gitorious:latest"
    sudo mkdir -p $HOST_DATA_DIR
    sudo docker run $PORT_OPTIONS $VOLUME_OPTIONS $OTHER_OPTIONS $IMAGE
    ;;
  stop)
    echo "Stopping Gitorious container..."
    [[ ! -f $CIDFILE ]] && echo "no $CIDFILE found" && exit 1
    sudo docker stop `cat $CIDFILE`
    sudo rm -f $CIDFILE
    ;;
  status)
    [[ -f $CIDFILE ]] || (echo "not running" && exit 1)
    CID=`cat $CIDFILE`
    sudo docker ps -q -notrunc | grep $CID >/dev/null && echo "running ($CID)" || (echo "not running" && exit 1)
    ;;
  ssh)
    cat ~/.ssh/id_rsa.pub | sudo tee /var/lib/gitorious/config/authorized_keys >/dev/null && ssh root@localhost -p $SSH_PORT
    ;;
  *)
    echo "usage: gitoriousctl start|stop|status|ssh"
    ;;
esac
