#!/bin/sh

mkdir -p /srv/gitorious/data/repositories

exec sudo -u git /usr/bin/git daemon --listen=0.0.0.0 --export-all --base-path=/srv/gitorious/data/repositories --verbose --reuseaddr /srv/gitorious/data/repositories
