user: git
frontend_server: nginx
client_host: <%= ENV['WEB_PORT_3000_TCP_ADDR'] || 'localhost' %>
client_port: <%= (ENV['WEB_PORT_3000_TCP_PORT'] || 3000).to_i %>
repository_base_path: /srv/gitorious/data/repositories
archive_cache_dir: /srv/gitorious/data/tarballs-cache
archive_work_dir: /srv/gitorious/data/tarballs-work
enable_repository_dir_sharding: false
messaging_adapter: resque
git_binary: /usr/bin/env git
