user: git
frontend_server: nginx
client_port: 3000
repository_base_path: /var/lib/gitorious/data/repositories
archive_cache_dir: /var/lib/gitorious/data/tarball-cache
archive_work_dir: /var/lib/gitorious/data/tarball-work
enable_repository_dir_sharding: false
messaging_adapter: resque
git_binary: /usr/bin/env git
